MVCProject/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ShopProject.DataAccess.Data.Repository.IRepository;
using ShopProject.Models;
using ShopProject.Models.ViewModels;
using ShopProject.Utility;
using System.Diagnostics;
using System.Security.Claims;

namespace MVCProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty] public OrderVM OrderVm { get; set; }

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVm = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(o => o.Id == orderId,
                    includeProperties: "ApplicationUser"),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(od => od.OrderHeaderId == orderId,
                    includeProperties: nameof(Product))
            };
            return View(OrderVm);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(o => o.Id == OrderVm.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVm.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVm.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVm.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVm.OrderHeader.City;
            orderHeaderFromDb.State = OrderVm.OrderHeader.State;
            orderHeaderFromDb.PostalCode = OrderVm.OrderHeader.PostalCode;

            if (!string.IsNullOrEmpty(OrderVm.OrderHeader.Carrier))
                orderHeaderFromDb.Carrier = OrderVm.OrderHeader.Carrier;

            if (!string.IsNullOrEmpty(OrderVm.OrderHeader.TrackingNumber))
                orderHeaderFromDb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;

            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();

            TempData["success"] = "Order Details Updated Successfully.";

            return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["success"] = "Order Status Updated Successfully.";

            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id);
            orderHeader.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
            orderHeader.Carrier = OrderVm.OrderHeader.Carrier;
            orderHeader.OrderStatus = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.OrderHeader.Update(orderHeader);
            _unitOfWork.Save();

            TempData["success"] = "Order Shipped Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id);

            if (orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled);
            }
            else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }

            _unitOfWork.Save();

            TempData["success"] = "Order Canceled Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
        }

        [HttpPost]
        [ActionName("Details")]
        public IActionResult DetailsPayNow()
        {
            OrderVm.OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id,
                includeProperties: nameof(ApplicationUser));
            OrderVm.OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.Id == OrderVm.OrderHeader.Id,
                includeProperties: nameof(Product));

            _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, OrderVm.OrderHeader.OrderStatus, SD.PaymentStatusApproved);
            _unitOfWork.Save();

            return View();
        }


        #region API Calls

        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> objOrderHeaders;


            if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
            {
                objOrderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                objOrderHeaders = _unitOfWork.OrderHeader.GetAll(o => o.ApplicationUserId == userId,
                    includeProperties: "ApplicationUser");
            }

            switch (status)
            {
                case "pending":
                    objOrderHeaders = objOrderHeaders.Where(o => o.PaymentStatus == SD.PaymentStatusDelayedPayment);
                    break;
                case "inprocess":
                    objOrderHeaders = objOrderHeaders.Where(o => o.OrderStatus == SD.StatusInProcess);
                    break;
                case "completed":
                    objOrderHeaders = objOrderHeaders.Where(o => o.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    objOrderHeaders = objOrderHeaders.Where(o => o.OrderStatus == SD.StatusApproved);
                    break;
                default:
                    break;
            }


            return Json(new { data = objOrderHeaders });
        }

        #endregion
    }
}

MVCProject/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopProject.DataAccess.Data.Repository;
using ShopProject.Models;
using ShopProject.Models.ViewModels;
using ShopProject.Utility;

namespace MVCProject.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class UserController : Controller
{
    private readonly UnitOfWork _unitOfWork;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly UserManager<IdentityUser> _userManager;

    public UserController(
        UnitOfWork unitOfWork,
        UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult RoleManagement(string userId)
    {
        RoleManagementVM RoleVM = new()
        {
            ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId, includeProperties: "Company"),
            RoleList = _roleManager.Roles.Select(i => new SelectListItem { Text = i.Name, Value = i.Name }),
            CompanyList = _unitOfWork.Company.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name, Value = i.Id.ToString()
            })
        };

        // Ensure ApplicationUser is not null before accessing properties
        if (RoleVM.ApplicationUser != null)
        {
            // Get the role name only if roleId is not null
            var role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == userId)).GetAwaiter()
                .GetResult();
            RoleVM.ApplicationUser.Role = role?.FirstOrDefault(); // Use null-conditional operator
        }
        else
        {
            // Handle case where ApplicationUser is not found
            return NotFound("Application user not found.");
        }

        return View(RoleVM);
    }

    [HttpPost]
    public IActionResult RoleManagement(RoleManagementVM roleManagementVm)
    {
        if (roleManagementVm?.ApplicationUser == null)
        {
            // Handle the error (e.g., return a BadRequest or similar response)
            return BadRequest("Invalid role management data.");
        }

        string? oldRole = _userManager
            .GetRolesAsync(_unitOfWork.ApplicationUser
                .Get(u => u.Id == roleManagementVm.ApplicationUser.Id)
            )
            .GetAwaiter()
            .GetResult()
            .FirstOrDefault();

        if (oldRole == null)
        {
            // Handle the case where the role is not found
            return NotFound("Role not found.");
        }

        ApplicationUser applicationUser =
            _unitOfWork.ApplicationUser
                .Get(u => u.Id == roleManagementVm.ApplicationUser.Id);

        if (roleManagementVm.ApplicationUser.Role != oldRole)
        {
            // a role was updated
           
            if (applicationUser == null)
            {
                // Handle the case where the application user is not found
                return NotFound("Application user not found.");
            }

            if (roleManagementVm.ApplicationUser.Role == SD.Role_Company)
            {
                applicationUser.CompanyId = roleManagementVm.ApplicationUser.CompanyId;
            }

            else if (oldRole == SD.Role_Company)
            {
                applicationUser.CompanyId = null;
            }
            _unitOfWork.ApplicationUser.Update(applicationUser);
            _unitOfWork.Save();

            _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
            _userManager.AddToRoleAsync(applicationUser, roleManagementVm.ApplicationUser.Role).GetAwaiter()
                .GetResult();
        }
        else if (oldRole == SD.Role_Company && applicationUser.CompanyId != roleManagementVm.ApplicationUser.CompanyId)
        {
            applicationUser.CompanyId = roleManagementVm.ApplicationUser.CompanyId;
            _unitOfWork.ApplicationUser.Update(applicationUser);
            _unitOfWork.Save();
        }


        return RedirectToAction(nameof(Index));
    }


    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        List<ApplicationUser> objApplicationUsers =
            _unitOfWork.ApplicationUser.GetAll(includeProperties: "Company").ToList();

        foreach (ApplicationUser user in objApplicationUsers)
        {
            user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

            user.Company ??= new Company() { Name = "" };
        }

        return Json(new { data = objApplicationUsers });
    }

    [HttpPost]
    public IActionResult LockUnlock([FromBody] string id)
    {
        var objFromDatabase = _unitOfWork.ApplicationUser
            .Get(u => u.Id == id);
        if (objFromDatabase == null)
        {
            return Json(new { success = true, message = "Error While Locking/Unlocking" });
        }

        if (objFromDatabase.LockoutEnd != null && objFromDatabase.LockoutEnd > DateTime.Now)
        {
            // user is currently locked and we want to unlock them
            objFromDatabase.LockoutEnd = DateTime.Now;
        }
        else
        {
            objFromDatabase.LockoutEnd = DateTime.Now.AddYears(1000);
        }
        _unitOfWork.ApplicationUser.Update(objFromDatabase);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Operation Successful" });
    }

    #endregion
}

MVCProject/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShopProject.DataAccess.Data.Repository.IRepository;
using ShopProject.Utility;
using System.Security.Claims;

namespace MVCProject.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
    private readonly IUnitOfWork _unitOfWork;

    public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        Claim? claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if (claim?.Value != null)
        {
            if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
            {
                HttpContext.Session.SetInt32(SD.SessionCart,
                    _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).Count());
            }

            return View(HttpContext.Session.GetInt32(SD.SessionCart));
        }
        else
        {
            HttpContext.Session.Clear();
            return View(0);
        }
    }
}

MVCProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/MVCProject.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.7/css/dataTables.dataTables.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCProject</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link text" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                    </li>
                    @if (User.IsInRole(SD.Role_Admin))
                    {
                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </button>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider"/>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                </li>
                            </ul>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                            @await Component.InvokeAsync("ShoppingCart")
                        </a>
                    </li>

                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer bg-primary">
    <div class="text-center text-light">
        Created with <i class="bi bi-heart-fill"></i> by Ali Mohammadinezhad
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.datatables.net/2.1.7/js/dataTables.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}